build:
    environment:
        php:
            version: 7.4
    nodes:
        analysis:
            environment:
                node: v14
            project_setup:
                override: true
            tests:
                override:
                    - php-scrutinizer-run --enable-security-analysis

checks:
    php:
        code_rating: true
        duplication: true

filter:
    paths: ["src/*"]
